# Generated by Django 4.2.4 on 2023-08-29 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_chat_alter_message_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ManyToManyField(blank=True, null=True, to='messenger.image'),
        ),
    ]
