# Generated by Django 4.2.4 on 2023-08-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_myuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
