# Generated by Django 4.2.4 on 2023-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
