# Generated by Django 4.2.4 on 2023-08-21 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_alter_resultanswer_result_alter_resultanswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanswer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
