# Generated by Django 4.2.4 on 2023-08-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_category_remove_quiz_consumer_quiz_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
    ]
