# Generated by Django 4.2.4 on 2023-08-21 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_remove_resultanswer_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='resultanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
